### ISSUE TITLE
Problem with union types

### ISSUE THREAD

**Issue by emattias** [rimeto/ts-optchain#10]
I have this 

```typescript
import React from 'react';

type HasA = {
  a: string;
};

type DataType = {
  bar: HasA | React.ComponentType;
};

const data: DataType = {
  bar: {},
};

oc(data).bar.a();

```

Which results in this error:
```
Error:(84, 14) TS2339: Property 'a' does not exist on type 'OCType<HasA | ComponentClass<{}, any> | StatelessComponent<{}>>'.
  Property 'a' does not exist on type 'IDataAccessor<HasA | ComponentClass<{}, any> | StatelessComponent<{}>> & ObjectWrapper<ComponentClass<{}, any>>'.
```

Is am not sure if this a bug in optchain or do I need to change my typings? 🤔

**Comment by wielrls** [comment]
Is an intersection type more appropriate for this situation?
```typescript
type DataType = {
  bar: HasA & React.ComponentType;
};
```

**Comment by emattias** [comment]
I fixed the problem. Thanks for making deep objects a type safe breeze!👌🏼

**Comment by hdennen** [comment]
Type assertion allows for checking values on potentially non-existent properties of one member of a union type. Is this a potential solution?
ie:
`oc(data).(<HasA>bar).a()`
