### ISSUE TITLE
Problem with properties of type 'any'

### ISSUE THREAD

**Issue by adwiens** [rimeto/ts-optchain#12]
I have been unable to access children of properties that have type 'any':

> Property does not exist on type 'OCType<any>'.
>   Property does not exist on type 'IDataAccessor<any>'.

Example: [https://stackblitz.com/edit/ts-optchain-any](https://stackblitz.com/edit/ts-optchain-any)

**Comment by dereklin** [comment]
It will be good if it can be fixed.  In the meantime, maybe you can use this workaround?:

```
import { oc } from 'ts-optchain';

const testVar: {a: any} = { a: { b: 'some value', c: 'hi' } };

const a: any = oc(testVar).a;
console.log(a.b());
```
https://stackblitz.com/edit/ts-optchain-any-aawyvi?file=index.ts

**Comment by wouterds** [comment]
I quickly tried this out (#28), working as expected. Looking forward to a release where this is included!

**Comment by wielrls** [comment]
released!

**Comment by wouterds** [comment]
Nice 👏🥳
