### ISSUE TITLE
Unsupported on IE11 even with Proxy polyfill due to arrow function syntax

### ISSUE THREAD

**Issue by pauloavelar** [rimeto/ts-optchain#13]
Hello. I have been using **ts-optchain** for a while in my back-end projects and recently decided to use it in an Angular application. This application must support IE11, so I basically use polyfills for everything ES6+. Angular CLI (Webpack) takes care of transpiling TS files, so it is all generally smooth.

Here is the problem:

- **ES6** is not supported by IE11 by default: this affects `Proxy` and arrow functions;
- `Proxy` can be polyfilled with [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill);
- Arrow functions can be transpiled, **however** Angular CLI does not transpile JS files, only TypeScript.

Therefore, the following snippet causes a **syntax error** on IE11:

```js
return new Proxy(((defaultValue) => (data == null ? defaultValue : data)), {
    get: (target, key) => {
        const obj = target();
        return oc(typeof obj === 'object' ? obj[key] : undefined);
    },
});
```

**I propose we change the target to `es5` on `tsconfig.json`.**  
This should enable arrow function transpilation. If this brings any unwanted behavior (_unlikely_) then it's simpler to just avoid arrow functions in the codebase.

I plan on submitting a pull request soon with the target change -- once it is tested.

**Comment by wielrls** [comment]
Resolved in v0.1.3

**Comment by venkateshparihar** [comment]
Can you mention me where  to placed proxy polyfills file i have know idea of it

**Comment by pauloavelar** [comment]
@venkateshparihar I was developing an Angular project, so I added (imported) the polyfill script in my `polyfills.ts`.

If you are using something else you can just add a script tag in your HTML file, preferably high up in the head tag. Take a look at [this guide](https://github.com/GoogleChrome/proxy-polyfill/blob/master/README.md#usage).

**Comment by venkateshparihar** [comment]
Can you give me the polyfills.ts file code
