### ISSUE TITLE
Mention Babel Plugin in the readme

### ISSUE THREAD

**Issue by epeli** [rimeto/ts-optchain#21]
Hi!

I use TypeScript mostly with the Babel TypeScript preset and too often I have to support IE11 still (#13). So I've created this babel plugin which removes the proxy usage:

https://github.com/epeli/babel-plugin-ts-optchain

It can be also used to add support for React Native on Android (#5).

I've tested it with transpiled upstream tests and they all pass:

https://github.com/epeli/babel-plugin-ts-optchain/blob/a2682beae7a3747c3ec8f91197eefafbcac57906/packages/babel-plugin-ts-optchain/__tests__/upstream-ts-optchain.test.js

Though I had to little bit modify the `oc()` usage https://github.com/epeli/babel-plugin-ts-optchain/commit/6fa317505e52cc5a7dde71a3a764694179e6b70a

**Comment by epeli** [comment]
And if you are interested we could ship this directly with ts-optchain as a babel macro. It would allow React Create App & TypeScript users to use it like this:

```ts
import { oc } from "ts-optchain/macro";
```

without any other configuration.

**Comment by epeli** [comment]
Just released the macro as a standalone npm module `ts-optchain.macro`

https://github.com/epeli/babel-plugin-ts-optchain#babel-macro

**Comment by wielrls** [comment]
Hi @epeli -- very interesting and clever underlying implementation! 

Have you also taken a look at our alternative: https://github.com/rimeto/ts-transform-optchain? Similar in concept, except using as TS custom code transformer vs Babel. 

I'm not opposed to including this with ts-optchain to support projects that have an established Babel transform pipeline. Perhaps it also makes sense to incorporate the TS custom transformer into a unified package to give developers additional flexibility for application. 

Do you want to prep a PR that incorporates the babel macro into this repo?

**Comment by epeli** [comment]
Yeah, I noticed the ts-transform but I don't use tsc to compile TypeScript code so it's no use to me :)

> Do you want to prep a PR that incorporates the babel macro into this repo?

Actually having maintained it a bit I don't think it would be fair to you. Implementation wise it's a whole lot more complicated than the `ts-optchain` itself so it's probably more buggy and needs more patches to be released. That's a burden I don't want you to have.

I would still appreciate a README mention a lot.
