### ISSUE TITLE
Triple slash reference, still the way to use the transformer or not?

### ISSUE THREAD

**Issue by brad-jones** [rimeto/ts-optchain#29]
I was using the now deprecated `ts-transform-optchain` with a triple slash reference like:

```ts
/// <reference types="ts-transform-optchain" />
```

Replacing it with:

```ts
/// <reference types="ts-optchain" />
```

Does not appear to work. If I import it like:

```ts
import { oc } from "ts-optchain";
```

With the transformer config of:

```json
{ "transform": "ts-optchain/transform" }
```

Will it still transform correctly or am I now using the proxy version?

**Comment by wielrls** [comment]
Hi @brad-jones  -- after the recent release you no longer need triple slash reference. 

Instead import `oc` from `ts-optchain` as you normally would and `ts-optchain/transform` will transpile your `oc(...)` references at compile time. You can confirm by inspecting your build code to verify `oc(...)` calls have been substituted as expected. This approach felt more intuitive as the code setup is the same whether you're using the proxy or transform version of ts-optchain...open to feedback if there's a more intuitive way to configure the package!

**Comment by brad-jones** [comment]
@wielrls that's totally fine just wanted to double check. Perhaps a note in the readme for those coming from the old `ts-transform-optchain` package would be handy.
