### ISSUE TITLE
React-Rative for android does not support `Proxy` object

### ISSUE THREAD

**Issue by amol-c** [rimeto/ts-optchain#5]
The library works great with iOS. But, for android, it keeps complaining that the Proxy doesn't exist.

Based on google search, it looks like Proxy is not supported on android because the JSCore is from 2014.  An alternative is to use JSC for android from [JSC](https://github.com/react-community/jsc-android-buildscripts) or use [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill). This is something i would be giving a try when i get to it.

<img width="258" alt="screen shot 2018-10-03 at 2 43 47 pm" src="https://user-images.githubusercontent.com/2050256/46431844-d3b91780-c71a-11e8-8ae6-876423cb60f7.png">

**Comment by wielrls** [comment]
@amol-c let us know if you get a chance to test either of the approaches you've identified. Would be great for this library to support RN android.

**Comment by mikfoo** [comment]
I'm pretty certain a polyfill won't work as Proxy is not really polyfillable. I tried the proxy-polyfill linked above just to be sure and it doesn't work at all in browsers that only support ES5 (like IE).

**Comment by fbartho** [comment]
I wrote a Ponyfill for Proxy for our Android uses, so I'm going to experiment to see if that's compatible here & report back.

**Comment by amol-c** [comment]
Hey guys, updating the [jscore](https://github.com/react-community/jsc-android-buildscripts) worked for android.

We were planning to update the JSCore either way due to its outdated nature in  react-native.

**Comment by soutot** [comment]
@fbartho Did it work?

**Comment by wielrls** [comment]
FYI we recently published an alternative approach to ts-optchain that eliminates the dependency on `Proxy`: https://github.com/rimeto/ts-transform-optchain

**Comment by fbartho** [comment]
React-native just upgraded the base JavaScriptCore to a modern version, but I haven’t yet verified if Proxy works!
